USE OFICINA;

-- ****** Criando VIEWS ******
CREATE VIEW CLIENTE_CARRO AS 
SELECT C.IDCLIENTE, C.NOME, C.CPF, C.SEXO, C.ENDERECO, C.BAIRRO, 
       R.COR, R.PLACA, R.MARCA, R.IDCARRO      
       FROM CLIENTE C 
INNER JOIN CARRO R ON C.IDCLIENTE = R.IDCLIENTE;

-- Visualizando VIEW
SELECT * FROM CLIENTE_CARRO;



CREATE VIEW CONSERTO_ESTOQUE_SERVICO AS
SELECT E.IDCONSERTO, E.IDCARRO AS ID_CARRO_SERVICO, E.QUANTIDADE,
	   T.PECA, T.VALOR,
       S.MECANICO, S.DATA_CHEGADA, S.DATA_SAIDA       
       FROM CONSERTO E
INNER JOIN CARRO R ON E.IDCARRO = R.IDCARRO
INNER JOIN ESTOQUE T ON E.IDESTOQUE = T.IDESTOQUE
INNER JOIN SERVICO S ON E.IDCONSERTO = S.IDCONSERTO;

SELECT * FROM CONSERTO_ESTOQUE_SERVICO;



-- Criando VIEW com Relatório final para análise.
CREATE VIEW RELATORIO AS 
SELECT * FROM CLIENTE_CARRO C
LEFT JOIN CONSERTO_ESTOQUE_SERVICO E ON C.IDCARRO = E.ID_CARRO_SERVICO;

SELECT * FROM RELATORIO;



-- ****** Criando Procedures *****


-- Criando procedure para inserir dados na tabela cliente
DELIMITER $
CREATE PROCEDURE INSERIR_DADOS_CLIENTE(P_NOME VARCHAR(45), P_CPF VARCHAR(11), P_SEXO ENUM('M', 'F'), 
                 P_TEL VARCHAR(11), P_ENDERECO VARCHAR(45), P_BAIRRO VARCHAR(30))

BEGIN
INSERT INTO CLIENTE VALUES (NULL, P_NOME, P_CPF, P_SEXO, P_TEL, P_ENDERECO, P_BAIRRO);

END 
$

DELIMITER ;

CALL INSERIR_DADOS_CLIENTE( 'TESTE', 'TESTE', 'M', 'TESTE', 'TESTE', 'TESTE');

SELECT * FROM CLIENTE;




-- Criando procedure para procurar por idcliente e trazer as informações do cliente
DELIMITER $
CREATE PROCEDURE BUSCA_IDCLIENTE(P_IDCLIENTE INT)
BEGIN

	SELECT * FROM CLIENTE WHERE IDCLIENTE = P_IDCLIENTE;
END
$

CALL BUSCA_IDCLIENTE(9);


-- ****** Criando Triggers *****



-- Criando Trigger para fazer backup quando for apagado alguma informação da tabela cliente
DELIMITER $
CREATE TRIGGER BKUP_CLIENTES
BEFORE DELETE ON CLIENTE
FOR EACH ROW 
BEGIN 

	INSERT INTO OFICINA.BACKUP_CLIENTE VALUES(NULL,OLD.IDCLIENTE,OLD.NOME,
	OLD.CPF,OLD.SEXO, OLD.TEL, OLD.ENDERECO, OLD.BAIRRO,  NOW(), CURRENT_USER(),'EXCLUIR');

END 
$

DELETE FROM CLIENTE WHERE IDCLIENTE = 23;

SELECT * FROM BACKUP_CLIENTE;





